name: appsy
description: "Пространство для работы и управления приложениями"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  business_layout:
    path: lib/business_layout
  models:
    path: lib/models

  flutter_bloc: ^8.1.6
  flutter_svg:
  url_launcher: ^6.3.1
  uni_links:
  flutter_native_splash:
  font_awesome_flutter: ^10.8.0
  intl:
  intl_utils:
  universal_html:
  timezone:
  flutter_native_timezone:
  cached_network_image:
  go_router: ^14.6.2
  cupertino_icons: ^1.0.8
  logger:
  pull_to_refresh: ^2.0.0
  focused_menu: ^1.0.5
  webview_flutter: ^4.10.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_launcher_icons:
  flutter_lints: ^5.0.0

flutter_intl:
  synthetic-package: false
  enabled: true
  main_locale: ru
  arb_dir: lib/ui_layout/app/localization/l10n
  output_dir: lib/ui_layout/app/localization/generate

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/icons/menu_bottom/
    - assets/icons/status/
    - assets/images/
    - assets/logo/

  fonts:
    - family: SBSansText
      fonts:
        - asset: assets/fonts/SB Sans Text.ttf
    - family: SBSansTextMedium
      fonts:
        - asset: assets/fonts/SB Sans Text Medium.ttf
    - family: SBSansTextSemibold
      fonts:
        - asset: assets/fonts/SB Sans Text Semibold.ttf
    - family: SBSansTextBold
      fonts:
        - asset: assets/fonts/SB Sans Text Bold.ttf

#flutter pub run flutter_native_splash:create
flutter_native_splash:
  #  background_image: 'assets_ai_giga/splash_screen/splash.png'
#  image: 'assets/logo/splash-robot.png'
#  branding: 'assets/logo/loading.png'
  color: "#181818"
  web_image_mode: center
  branding_mode: bottom
  fullscreen: true

#flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/icon-app.png"
  remove_alpha_ios: true
  min_sdk_android: 21