name: appsy
description: "Все приложения в одном месте"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  business_layout:
    path: lib/business_layout
  models:
    path: lib/models

  flutter_bloc: ^8.1.6
  flutter_svg:
  url_launcher: ^6.3.1
  uni_links:
  flutter_native_splash: ^2.4.3
  font_awesome_flutter: ^10.8.0
  intl:
  universal_html:
  timezone:
  flutter_native_timezone:
  cached_network_image:
  go_router: ^14.6.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

#flutter pub run flutter_native_splash:create
flutter_native_splash:
  #  background_image: 'assets_ai_giga/splash_screen/splash.png'
  image: 'assets/splash_screen/splash-robot.png'
  branding: 'assets/splash_screen/loading.png'
  color: "#181818"
  web_image_mode: center
  branding_mode: bottom
  fullscreen: true